### ISSUE TITLE
Doesn't work in prod mode

### ISSUE THREAD

**Issue by opetriienko** [beyerleinf/ngx-dnd#1]
When I run `ng build --prod`
I see the error: 

> ERROR in: Unexpected value 'undefined' exported by the module 'DndModule in /Users/<user_name>/projects/new-app/node_modules/@beyerleinf/ngx-dnd/beyerleinf-ngx-dnd.d.ts'.

And the project becomes broken, so it can't be built in `prod` mode.

**Comment by beyerleinf** [comment]
Thansk for submitting an issue.

I'll have a look at it asap!

**Comment by beyerleinf** [comment]
Can you please provide more information about your project setup? I just tested this and I can't reproduce it right now.

Please run `ng -v` from within your project folder. Maybe you can also provide some code e.g. from where you import the DndModule.

Thank you for contributing!

**Comment by opetriienko** [comment]
@beyerleinf please, see:
https://github.com/opetriienko/test-dnd

The only thing I've added there - imported DndModule to AddModule imports. 

You can see the error when run: `npm run build:prod`

**Comment by beyerleinf** [comment]
You forgot to call `DndModule.forRoot()` in the imports array. (see [https://github.com/beyerleinf/ngx-dnd#2-import-the-dndmodule](https://github.com/beyerleinf/ngx-dnd#2-import-the-dndmodule)

**Comment by opetriienko** [comment]
@beyerleinf actually I have `forRoot` in my work project... 
I've also just added it in my test project https://github.com/opetriienko/test-dnd 

Have you tested it with `forRoot` and it worked for you in prod mode? I tested it with `forRoot` and see no difference. 

UPD: Sorry, I've forgotten to mention...I see an error: `ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.`

But the following error I found when I was debugging `ng build --prod` command via node debugger... :)
`

> The ERROR in: Unexpected value 'undefined' exported by the module 'DndModule in /Users/<user_name>/projects/new-app/node_modules//beyerleinf-ngx-dnd.d.ts'.

**Comment by beyerleinf** [comment]
Funny enough on the test project I created this worked perfectly fine. Using your project I only get the error `ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.` I don't get the other error at all. I'll try to investigate further.

**Comment by opetriienko** [comment]
@beyerleinf do you mean it works perfectly fine when you run `ng build --prod` or `ng serve`?
Cause for `ng serve` it works for me either.

1) `ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.`

^ This error you would see if you have `.forRoot()` in imports.

2) `ERROR in : Unexpected value 'undefined' exported by the module 'DndModule in /Users/<user_name>/projects/test-dnd/node_modules/@beyerleinf/ngx-dnd/beyerleinf-ngx-dnd.d.ts'`

^ This error you would see if you remove `.forRoot()` from imports.

**Comment by opetriienko** [comment]
Actually, I see the same error in this repo: https://github.com/beyerleinf/ngx-dnd/
I've just cloned it and ran: `npm run build.all` and see the same error in when it runs > `ng build demo --prod` under the hood

**Comment by beyerleinf** [comment]
As for the first question: both, actually.

I'll have a look at it tomorrow.

**Comment by LRNida** [comment]
I'm getting the same errors in my project when trying to use this module. Just running my project with `ng serve --aot`:
```
ERROR in : Unexpected value 'undefined' exported by the module 'DndModule in /Users/lrn/Documents/Projects/Barco.nosync/qaweb-webclient/node_modules/@beyerleinf/ngx-dnd/beyerleinf-ngx-dnd.d.ts'

ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
```

I made sure the `.forRoot()` is present, though i have to import the module via my shared module since we're using a number of lazy-loaded modules. 
Ps: there is a typo in the path for the css import in your readme 😉 should be `node_modules/@beyerleinf/ngx-dnd/styles.css`

**Comment by beyerleinf** [comment]
Okay, so I seem to have a made a mistake refactoring the code so I rolled back to the original code. I've released a new version as `@beyerleinf/ngx-dnd@6.0.0-preview3`. Please test it out and I will try to resolve the issue with refactored code :)

**Comment by opetriienko** [comment]
@beyerleinf this one works fine, thanks!
Looking forward to seeing the refactored one... 😉

**Comment by beyerleinf** [comment]
@opetriienko Glad, it works! Me too! The code is pretty messy IMHO...

**Comment by dominikhb** [comment]
@beyerleinf thank you. It works for me, too. I tried myself to remove all barrel files (index.ts) and refactor the imports. Then it worked.
A good indicator that something is wrong, is to look into the `dist/lib/beyerleinf-ngx-dnd.d.ts` file. If there are additional import to the public_api, that is bad.

**Comment by beyerleinf** [comment]
@dominikhb Thank you for that hint! That will come in handy. I hope to get some work done through the weekend.
