### ISSUE TITLE
Dragging (nested)components in a sortable container takes ~10s

### ISSUE THREAD

**Issue by LRNida** [beyerleinf/ngx-dnd#2]
**Describe the bug**
I am using the sortable container functionality to enable drag and drop on my dashboard in a flex grid. To dynamically generate the widgets I'm using a wrapper element in combination with ngFor that instantiates the widget componens based on the data passed to it.
The drag and drop does work in this instance, however it literally takes ~10 seconds to resolve (see screenshot).
My guess is that the problem is in the method(s) that calculate(s) the new index of the sorted item.

**To Reproduce**
1. Create a list of nested components 
2. Make the container of the list a sortable-container
3. Attach drag start & drop success callbacks to log events
4. Watch timestamps of the logged events

**Expected behavior**
The time should drastically drease to make the library user-friendly or there should be a notice not to try it with lists of nested components. 

**Screenshots**
<img width="429" alt="screen shot 2018-06-15 at 15 14 57" src="https://user-images.githubusercontent.com/24736490/41471188-3761e44c-70b3-11e8-865e-a8e2e4d271e6.png">

**Example Code**
Please provide some example code to help us understand the issue.

**Desktop (please complete the following information):**
 - OS: OSX High Sierra 10.13.4
 - Browser Firefox 60
 - Version preview3

**Comment by beyerleinf** [comment]
Thanks for creating this issue!

Could you show me sample project or some code from your components so I can have a look at it?

**Comment by LRNida** [comment]
I couldn't get a plunker up without too much hassle, so I hope this will help reproducing the issue. It's some simplified code of what we're using: [sample code.txt](https://github.com/beyerleinf/ngx-dnd/files/2106427/sample.code.txt)
I didn't include the code of the widgets themselves, though I can supply that too if need be.

PS. thanks for creating this fork, would've had to recode a rather complicated tree component with workarounds if it wasn't for this.

**Comment by beyerleinf** [comment]
Gotta give back to the community somehow, right? :smile: 

So, I created a demo project at [https://github.com/beyerleinf/test-dnd](https://github.com/beyerleinf/test-dnd). Please clone it and take a look yourself. I can't seem to repoduce it but maybe I didn't understand something quite right.

My first thought was, that the component creation was an issue but I didn't notice anything. Maybe it's something you do inside the widgets? If you have a repo I can look at I can maybe help you out.

**Comment by LRNida** [comment]
Thanks for checking that out so quickly 😃 
Your comment about not being able to reproduce it and weekend rest gave me an idea: maybe there were too many change detections going on. 

So I changed the change detection strategy to OnPush at the level of my wrapper component (and marking observable subscriptions for check inside the widget) and now everything works nice and fast. Might be handy to know for anyone trying out anything similar.
Sorry for kind of wasting some of your time since the problem was on my end 😅

**Comment by beyerleinf** [comment]
Not a problem at all :D I could've imagined that something could be wrong on my side

**Comment by NDDT-B5** [comment]
I have the same issue, even with just running the sample code (number 9).

I put chageDetection OnPush but that should not make a diffrence to the sample code as that array is only defined in the same component.

**Comment by beyerleinf** [comment]
@NDDT-B5 Could you provide me with a small repo to reproduce it? That would be very much appreciated! :)

**Comment by NDDT-B5** [comment]
I will try to create a minimal example. Thank you

**Comment by beyerleinf** [comment]
I've just released the RC. Please install it with `npm i -S @beyerleinf/ngx-dnd@next` and test again :)

**Comment by NDDT-B5** [comment]
Hi, thanks for the update. There is definitly a noticable pick up in speed,

But also other components are not notified of changes anymore. I don't know if that could be an issue for others. I think I can work arround this.

**Comment by beyerleinf** [comment]
If you provide a small reproduction repo I could try to help you :) But I'm glad my refactoring helped a bit.

**Comment by beyerleinf** [comment]
Any news on this?

**Comment by beyerleinf** [comment]
Closed due to inactivity
