### ISSUE TITLE
I need to have a callback like "onSortSuccess"

### ISSUE THREAD

**Issue by andreadompe** [beyerleinf/ngx-dnd#44]
**Is your feature request related to a problem? Please describe.**
I have the same situation like "Simple sortable with Drag-and-Drop " (example 7) 
i would like to add a function every time a user sort an element

**Describe the solution you'd like**
i need to have a callback/event on every sort action.

**Describe alternatives you've considered**

**Additional context**

**Comment by beyerleinf** [comment]
Hi @andreadompe! Thanks for creating this issue. The feature you are looking for is already implemented but as it seems not documented well enough (or not at all).
Please see [this example repo](https://github.com/beyerleinf/test-dnd/tree/master/src/app/issue-44/issue-fourtyfour) on how to use it :)

If this is not what you are looking for feel free to reply and we will sort this out :)

**Comment by andreadompe** [comment]
This is exactly what i need!!!
Thank you so much!

**Comment by beyerleinf** [comment]
Perfect! I will definitely improve the documentation for the release :D
