### ISSUE TITLE
Zone restiction for multiple sortable lists

### ISSUE THREAD

**Issue by andreadompe** [beyerleinf/ngx-dnd#48]
**Is your feature request related to a problem? Please describe.**
I have the same situation like "Simple sortable with Drag-and-Drop " (example 7)
i have 2 or more sortable lists, actually i can drag an element from a sortable list and drop into another sortable list.

**Describe the solution you'd like**
I would like to restrict every element of each lists to be droppable ONLY in its list

**Describe alternatives you've considered**

**Additional context**

**Comment by beyerleinf** [comment]
Hi! You can simply give each sortable list a different drop zone name.

```
<ul dnd-sortable-container [dropZones]="['zone1']" [sortableData]="list1">
  <li *ngFor="let item of list1; let i = index" dnd-sortable [sortableIndex]="i">{{item}}</li>
</ul>

<ul dnd-sortable-container [dropZones]="['zone2']" [sortableData]="list2">
  <li *ngFor="let item of list2; let i = index" dnd-sortable [sortableIndex]="i">{{item}}</li>
</ul>
```

Is this what you want? I will note that in the list of demos I need to create

**Comment by andreadompe** [comment]
Yes, is what I need, I've already try it, but these sortable lists are created in angular with a ngFor,  so I've tried to interpolate the nameZone but I get an error of interpolation

**Comment by beyerleinf** [comment]
If you have a name you can only do it like `[dropZones]="[myVariable]"` or `dropZones="['{{myVariable}}']"`.

**Comment by andreadompe** [comment]
I've already tried this way (`dropZones="['{{myVariable}}']"`) but there is a problem,
in angular {{}} never goes together with [prop]="..." or (event)="..." because ther is an interpolation error as you can see [there](https://stackoverflow.com/questions/42456459/got-interpolation-where-expression-was-expected)
So i've tried this way

**template**
`[dropZones]="getCategoryIdForDropZones(category)" dnd-sortable-container...`

**component**
`	getCategoryIdForDropZones(category: any) {
		return `${category.id}`;
	}
`

and the interpolation problem is fixed!
In the inspection window i can see ng-reflect-dropzones="Ms0MKEP2GbqXpDqOsd1n"
so effectively each dnd-sortable-container has its own dropZone!

But i can continue to move items from a list to the others...

**Comment by beyerleinf** [comment]
Ok, so I tried to recreate what you are doing. Seems only part of my last comment was correct but you could do it without creating a function. Your function wasn't working because you didn't return `string[]`. I personally prefer doing thing without a function if possible but that's up to you.

See [this example](https://github.com/beyerleinf/test-dnd/tree/master/src/app/issue-48/restricted-sortable-zones-interpolation) on how I did it

**Comment by andreadompe** [comment]
Fantastic!
now i return string[] and all work perfectly!
Thank you so much!
