### ISSUE TITLE
Nested sortable lists

### ISSUE THREAD

**Issue by andreadompe** [beyerleinf/ngx-dnd#53]
**Is your feature request related to a problem? Please describe.**
I ned to sort nested items inside a sortable list, i have a nested sortable list [https://angular-hgtpmp.stackblitz.io](stackblitz), i can sort the main category bat i need also to sort the nested products

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://angular-hgtpmp.stackblitz.io

**Comment by beyerleinf** [comment]
I will look into it but I can't promise you a quick fix

**Comment by beyerleinf** [comment]
Hi, I'm sorry your issue has been open for such a long time. Today I might have a solution for you.

Please check out [this demo repo](https://github.com/beyerleinf/angular-native-drag-drop-demo). More specifically [the example about embedded sorting](https://github.com/beyerleinf/angular-native-drag-drop-demo/tree/master/src/app/sorting/embedded-sorting). You can simply clone the repo and check the example out by running `ng serve`. I think the better solution is to use Angular CDK for your use case.

Don't hesitate getting back to me or shoot me an email if you have any question.
