### ISSUE TITLE
[Firefox] dropping clickable element on not-allowed dropzone triggers click

### ISSUE THREAD

**Issue by LRNida** [beyerleinf/ngx-dnd#6]
**Describe the bug**
**seen in Firefox**
Droping a dnd-draggable onto a dnd-droppable that has [allowDrop] evaluate to false triggers a click event on the dnd-draggable. 
When dropping anywhere else, this does not happen. It also does not happen on chrome.

**To Reproduce**
1. Turn an <a> tag with [routerLink] into a dnd-draggable.
2. Set up a dnd-droppable zone but leave space outside of the zone too.
3. Set the dnd-droppable's [allowDrop] to false.
4. Drop the draggable link outside the drop zone (no effect) then drop it on the not-allowed drop zone and it should trigger the link.

**Expected behavior**
Since the click is not triggered when dropping on random location, it should also not trigger when dropping on a not allowed dropzone.

**Desktop (please complete the following information):**
 - OS: OSX 10.13.5
 - Browser Firefox 61.0.1
 - Version ngx-dnd preview3

**Additional context**
Seems at first sight to be a Firefox related issue, doesn't happen on chrome.

**Comment by beyerleinf** [comment]
Thanks for creating this issue. I will have a look at it over the weekend. Could you update to the current RC in the meantime? `npm i -S @beyerleinf/ngx-dnd@next` And maybe post some example code or create a small reproduction repo :) Thanks!

**Comment by LRNida** [comment]
I'll test the update right away :) I'll see if I can create an example repo later today.
Also, when hovering over different dropzones our app also slowed down very very hard, but only in Firefox (not tested on safari or edge yet). So there might be more issues with FF drag and drop. Don't think many users of our project use firefox so the impact probably won't be that great for us.

**Comment by beyerleinf** [comment]
While testing I discovered a possible bug because allowDrop isn't working on the RC for me right now

**Comment by beyerleinf** [comment]
Any news on this?

**Comment by beyerleinf** [comment]
Closed due to inactivity.
