### ISSUE TITLE
Update to Angular 8

### ISSUE THREAD

**Issue by skrtheboss** [beyerleinf/ngx-dnd#75]
**Is your feature request related to a problem? Please describe.**
I have update the Angular version in my project, but ngx-dnd keeps asking for angular 7.

**Describe the solution you'd like**
Upgrade Angular to version 8

**Comment by beyerleinf** [comment]
Hi and thanks for creating an issue. I will try to make a new release that has Angular 8 as a peerDependency this weekend. Please hang in there because I'm currently on a business trip :)

**Comment by skrtheboss** [comment]
Hi, thanks for the quick feedback. Looking forward to a new release.

**Comment by beyerleinf** [comment]
The new version is published.

Things to keep in mind: I've added a notice recommending switching to native drag and drop using Angular CDK which is definitely the recommended way. I'm working on a demo repo which shows how to recreate the examples from here using Angular CDK.

I will add a link in this README and the postinstall notice to the demo repo once I've gotten far enough.
