### ISSUE TITLE
Angular 7 compatibility, launch issue

### ISSUE THREAD

**Issue by FrolovSD** [beyerleinf/ngx-dnd#89]
**Describe the bug**
Hi, I have angular 7 project. After installing the package by "npm install @beyerleinf/ngx-dnd" and launching the project I get the following:
WARNING in ./node_modules/@beyerleinf/ngx-dnd/fesm5/beyerleinf-ngx-dnd.js 38:56-74
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
WARNING in ./node_modules/@beyerleinf/ngx-dnd/fesm5/beyerleinf-ngx-dnd.js 53:57-75
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
WARNING in ./node_modules/@beyerleinf/ngx-dnd/fesm5/beyerleinf-ngx-dnd.js 899:65-83
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
WARNING in ./node_modules/@beyerleinf/ngx-dnd/fesm5/beyerleinf-ngx-dnd.js 899:175-183
"export 'ɵɵinject' was not found in '@angular/core'

And in runtime: Uncaught TypeError: Object(...) is not a function

It seems the warnings point out that installed package version is for angular 8 project.
Ok, I've reinstalled the package by "npm install @beyerleinf/ngx-dnd@ng7" and still getting the same issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/22049690/67207872-d8d42c00-f42d-11e9-92d4-f454bf21001a.png)

**Comment by chorpler** [comment]
I had the same problem this morning. It looks like even versions 6 and 7 got built with Angular 8-specific settings. I ended up just cloning the v7 branch of the repo, building it locally with Angular 7, and importing that instead of the published `@beyerleinf/ngx-dnd@ng7` package, at least for now.

**Comment by beyerleinf** [comment]
It appears that you both are 100% correct. I think what happened was, that I didn't delete the node_modules folder after switching branches... Shame on me 😞 I'm going to publish new versions and then close this issue.

Please note that there will *not* be a specifically Angular 9 compatible version as the solution using Angular CDK seems to be more viable in the long run. If you have any questions regarding this, please send me an email :)

**Comment by beyerleinf** [comment]
New versions have been published!

**Comment by FrolovSD** [comment]
It works, thank you so much!
