### ISSUE TITLE
Angular 6 + ngx-dnd + scss not working

### ISSUE THREAD

**Issue by HarelM** [beyerleinf/ngx-dnd#9]
**Describe the bug**
I can't make my scss file find the css file from this repository.

**To Reproduce**
Create an angular project with --style=scss, and try importing the css file inside style.scss

**Expected behavior**
The file should be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/3269297/43230184-0f3ab44e-9070-11e8-8da3-5b8fc576f2c7.png)

**Example Code**
https://stackblitz.com/edit/angular-6-ngx-dnd-scss

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] cli

**Smartphone (please complete the following information):**

**Additional context**
I know I can probably add it to the angular.json file, but I prefer to do all my imports inside the main scss file so that I have it in one place.
Plus I'm able to do it for other libraries so I don't see a reason it should not work in this library...

**Comment by beyerleinf** [comment]
You forgot the "s" in ` styles.css` (see [Readme](https://github.com/beyerleinf/ngx-dnd#1-add-the-default-styles)) :) Thanks for making such a detailed issue, though :)

**Comment by HarelM** [comment]
Thanks for the quick response, seems that I made this mistake in both the reproduction version and my own code... :-/ embarrassing...
